2017-02-23T22:22:31.953-0500 I CONTROL  [initandlisten] MongoDB starting : pid=3080 port=27001 dbpath=/home/lrodriguez/Curso Mongo University 102 MongoDb For DBA/final_exam/data/z1 64-bit host=localhost.localdomain
2017-02-23T22:22:31.953-0500 I CONTROL  [initandlisten] db version v3.4.0-rc3
2017-02-23T22:22:31.953-0500 I CONTROL  [initandlisten] git version: 7d68067e5a6272bb463acc4e7a6c6a144148039c
2017-02-23T22:22:31.953-0500 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
2017-02-23T22:22:31.953-0500 I CONTROL  [initandlisten] allocator: tcmalloc
2017-02-23T22:22:31.953-0500 I CONTROL  [initandlisten] modules: none
2017-02-23T22:22:31.953-0500 I CONTROL  [initandlisten] build environment:
2017-02-23T22:22:31.953-0500 I CONTROL  [initandlisten]     distmod: rhel70
2017-02-23T22:22:31.953-0500 I CONTROL  [initandlisten]     distarch: x86_64
2017-02-23T22:22:31.953-0500 I CONTROL  [initandlisten]     target_arch: x86_64
2017-02-23T22:22:31.953-0500 I CONTROL  [initandlisten] options: { net: { port: 27001 }, processManagement: { fork: true }, replication: { oplogSizeMB: 50, replSet: "z" }, storage: { dbPath: "data/z1", mmapv1: { smallFiles: true } }, systemLog: { destination: "file", path: "a.log" } }
2017-02-23T22:22:31.953-0500 W -        [initandlisten] Detected unclean shutdown - /home/lrodriguez/Curso Mongo University 102 MongoDb For DBA/final_exam/data/z1/mongod.lock is not empty.
2017-02-23T22:22:32.001-0500 I -        [initandlisten] Detected data files in /home/lrodriguez/Curso Mongo University 102 MongoDb For DBA/final_exam/data/z1 created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2017-02-23T22:22:32.001-0500 W STORAGE  [initandlisten] Recovering data from the last clean checkpoint.
2017-02-23T22:22:32.001-0500 I STORAGE  [initandlisten] 
2017-02-23T22:22:32.001-0500 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2017-02-23T22:22:32.001-0500 I STORAGE  [initandlisten] See http://dochub.mongodb.org/core/prodnotes-filesystem
2017-02-23T22:22:32.001-0500 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=5095M,session_max=20000,eviction=(threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2017-02-23T22:22:33.037-0500 I STORAGE  [initandlisten] Starting WiredTigerRecordStoreThread local.oplog.rs
2017-02-23T22:22:33.037-0500 I STORAGE  [initandlisten] The size storer reports that the oplog contains 151 records totaling to 14546 bytes
2017-02-23T22:22:33.037-0500 I STORAGE  [initandlisten] Scanning the oplog to determine where to place markers for truncation
2017-02-23T22:22:33.104-0500 W STORAGE  [initandlisten] Detected configuration for non-active storage engine mmapv1 when current storage engine is wiredTiger
2017-02-23T22:22:33.104-0500 I CONTROL  [initandlisten] 
2017-02-23T22:22:33.104-0500 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2017-02-23T22:22:33.104-0500 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2017-02-23T22:22:33.104-0500 I CONTROL  [initandlisten] 
2017-02-23T22:22:33.116-0500 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/home/lrodriguez/Curso Mongo University 102 MongoDb For DBA/final_exam/data/z1/diagnostic.data'
2017-02-23T22:22:33.117-0500 I NETWORK  [thread1] waiting for connections on port 27001
2017-02-23T22:22:33.118-0500 W NETWORK  [replExecDBWorker-0] Failed to connect to 127.0.0.1:27002, reason: Connection refused
2017-02-23T22:22:33.119-0500 W NETWORK  [replExecDBWorker-0] Failed to connect to 127.0.0.1:27003, reason: Connection refused
2017-02-23T22:22:33.119-0500 I REPL     [replExecDBWorker-0] New replica set config in use: { _id: "z", version: 1, protocolVersion: 1, members: [ { _id: 1, host: "localhost:27001", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 }, { _id: 2, host: "localhost:27002", arbiterOnly: true, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 }, { _id: 3, host: "localhost:27003", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 } ], settings: { chainingAllowed: true, heartbeatIntervalMillis: 2000, heartbeatTimeoutSecs: 10, electionTimeoutMillis: 10000, catchUpTimeoutMillis: 2000, getLastErrorModes: {}, getLastErrorDefaults: { w: 1, wtimeout: 0 }, replicaSetId: ObjectId('58ae563b1435ca67253508bf') } }
2017-02-23T22:22:33.119-0500 I REPL     [replExecDBWorker-0] This node is localhost:27001 in the config
2017-02-23T22:22:33.119-0500 I REPL     [replExecDBWorker-0] transition to STARTUP2
2017-02-23T22:22:33.119-0500 I REPL     [replExecDBWorker-0] Starting replication storage threads
2017-02-23T22:22:33.121-0500 I REPL     [replExecDBWorker-0] Starting replication fetcher thread
2017-02-23T22:22:33.121-0500 I REPL     [replExecDBWorker-0] Starting replication applier thread
2017-02-23T22:22:33.121-0500 I REPL     [replExecDBWorker-0] Starting replication reporter thread
2017-02-23T22:22:33.122-0500 I REPL     [rsSync] transition to RECOVERING
2017-02-23T22:22:33.122-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27002
2017-02-23T22:22:33.123-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27002 - HostUnreachable: Connection refused
2017-02-23T22:22:33.165-0500 E REPL     [rsBackgroundSync] sync producer problem: 2 required optime (if provided) must be more recent than last fetched optime. requiredOpTime: { ts: Timestamp 1487821821000|1, t: 1 }, lastOpTimeFetched: { ts: Timestamp 1487821821000|1, t: 1 }
2017-02-23T22:22:33.165-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27003
2017-02-23T22:22:33.165-0500 I REPL     [ReplicationExecutor] Error in heartbeat request to localhost:27002; HostUnreachable: Connection refused
2017-02-23T22:22:33.166-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27002
2017-02-23T22:22:33.166-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27003 - HostUnreachable: Connection refused
2017-02-23T22:22:33.166-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27002 - HostUnreachable: Connection refused
2017-02-23T22:22:33.166-0500 I REPL     [ReplicationExecutor] Error in heartbeat request to localhost:27003; HostUnreachable: Connection refused
2017-02-23T22:22:33.167-0500 I REPL     [ReplicationExecutor] Error in heartbeat request to localhost:27002; HostUnreachable: Connection refused
2017-02-23T22:22:33.167-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27003
2017-02-23T22:22:33.167-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27003 - HostUnreachable: Connection refused
2017-02-23T22:22:33.167-0500 I REPL     [ReplicationExecutor] Error in heartbeat request to localhost:27003; HostUnreachable: Connection refused
2017-02-23T22:22:33.167-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27002
2017-02-23T22:22:33.167-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27003
2017-02-23T22:22:33.168-0500 I REPL     [rsSync] transition to SECONDARY
2017-02-23T22:22:33.168-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27002 - HostUnreachable: Connection refused
2017-02-23T22:22:33.168-0500 I REPL     [ReplicationExecutor] Error in heartbeat request to localhost:27002; HostUnreachable: Connection refused
2017-02-23T22:22:33.168-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27003 - HostUnreachable: Connection refused
2017-02-23T22:22:33.169-0500 I REPL     [ReplicationExecutor] Error in heartbeat request to localhost:27003; HostUnreachable: Connection refused
2017-02-23T22:22:34.012-0500 I FTDC     [ftdc] Unclean full-time diagnostic data capture shutdown detected, found interim file, some metrics may have been lost. OK
2017-02-23T22:22:38.168-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27002
2017-02-23T22:22:38.169-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27002 - HostUnreachable: Connection refused
2017-02-23T22:22:38.169-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27003
2017-02-23T22:22:38.169-0500 I REPL     [ReplicationExecutor] Error in heartbeat request to localhost:27002; HostUnreachable: Connection refused
2017-02-23T22:22:38.169-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27002
2017-02-23T22:22:38.170-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27003 - HostUnreachable: Connection refused
2017-02-23T22:22:38.170-0500 I REPL     [ReplicationExecutor] Error in heartbeat request to localhost:27003; HostUnreachable: Connection refused
2017-02-23T22:22:38.170-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27002 - HostUnreachable: Connection refused
2017-02-23T22:22:38.170-0500 I REPL     [ReplicationExecutor] Error in heartbeat request to localhost:27002; HostUnreachable: Connection refused
2017-02-23T22:22:38.170-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27003
2017-02-23T22:22:38.171-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27002
2017-02-23T22:22:38.172-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27003 - HostUnreachable: Connection refused
2017-02-23T22:22:38.172-0500 I REPL     [ReplicationExecutor] Error in heartbeat request to localhost:27003; HostUnreachable: Connection refused
2017-02-23T22:22:38.172-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27002 - HostUnreachable: Connection refused
2017-02-23T22:22:38.172-0500 I REPL     [ReplicationExecutor] Error in heartbeat request to localhost:27002; HostUnreachable: Connection refused
2017-02-23T22:22:38.172-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27003
2017-02-23T22:22:38.173-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27003 - HostUnreachable: Connection refused
2017-02-23T22:22:38.173-0500 I REPL     [ReplicationExecutor] Error in heartbeat request to localhost:27003; HostUnreachable: Connection refused
2017-02-23T22:22:43.173-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27002
2017-02-23T22:22:43.173-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27003
2017-02-23T22:22:43.174-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27002 - HostUnreachable: Connection refused
2017-02-23T22:22:43.174-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27003 - HostUnreachable: Connection refused
2017-02-23T22:22:43.174-0500 I REPL     [ReplicationExecutor] Error in heartbeat request to localhost:27002; HostUnreachable: Connection refused
2017-02-23T22:22:43.174-0500 I REPL     [ReplicationExecutor] Error in heartbeat request to localhost:27003; HostUnreachable: Connection refused
2017-02-23T22:22:43.174-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27002
2017-02-23T22:22:43.174-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27003
2017-02-23T22:22:43.175-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27002 - HostUnreachable: Connection refused
2017-02-23T22:22:43.175-0500 I REPL     [ReplicationExecutor] Error in heartbeat request to localhost:27002; HostUnreachable: Connection refused
2017-02-23T22:22:43.175-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27002
2017-02-23T22:22:43.175-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27003 - HostUnreachable: Connection refused
2017-02-23T22:22:43.176-0500 I REPL     [ReplicationExecutor] Error in heartbeat request to localhost:27003; HostUnreachable: Connection refused
2017-02-23T22:22:43.176-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27003
2017-02-23T22:22:43.176-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27002 - HostUnreachable: Connection refused
2017-02-23T22:22:43.176-0500 I REPL     [ReplicationExecutor] Error in heartbeat request to localhost:27002; HostUnreachable: Connection refused
2017-02-23T22:22:43.176-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27003 - HostUnreachable: Connection refused
2017-02-23T22:22:43.176-0500 I REPL     [ReplicationExecutor] Error in heartbeat request to localhost:27003; HostUnreachable: Connection refused
2017-02-23T22:22:43.890-0500 I REPL     [ReplicationExecutor] Not starting an election, since we are not electable due to: Not standing for election because I cannot see a majority (mask 0x1)
2017-02-23T22:22:47.330-0500 I NETWORK  [thread1] connection accepted from 127.0.0.1:55686 #1 (1 connection now open)
2017-02-23T22:22:47.331-0500 I -        [conn1] end connection 127.0.0.1:55686 (1 connection now open)
2017-02-23T22:22:47.334-0500 I NETWORK  [thread1] connection accepted from 127.0.0.1:55694 #2 (1 connection now open)
2017-02-23T22:22:47.334-0500 I NETWORK  [conn2] received client metadata from 127.0.0.1:55694 conn2: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.0-rc3" }, os: { type: "Linux", name: "Fedora release 24 (Twenty Four)", architecture: "x86_64", version: "Kernel 4.6.7-300.fc24.x86_64" } }
2017-02-23T22:22:48.176-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27002
2017-02-23T22:22:48.177-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27003
2017-02-23T22:22:48.178-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27003 - HostUnreachable: Connection refused
2017-02-23T22:22:48.178-0500 I REPL     [ReplicationExecutor] Error in heartbeat request to localhost:27003; HostUnreachable: Connection refused
2017-02-23T22:22:48.179-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:27002
2017-02-23T22:22:48.179-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27003
2017-02-23T22:22:48.179-0500 I REPL     [ReplicationExecutor] Member localhost:27002 is now in state ARBITER
2017-02-23T22:22:48.180-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27003 - HostUnreachable: Connection refused
2017-02-23T22:22:48.180-0500 I REPL     [ReplicationExecutor] Error in heartbeat request to localhost:27003; HostUnreachable: Connection refused
2017-02-23T22:22:48.180-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27003
2017-02-23T22:22:48.181-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27003 - HostUnreachable: Connection refused
2017-02-23T22:22:48.181-0500 I REPL     [ReplicationExecutor] Error in heartbeat request to localhost:27003; HostUnreachable: Connection refused
2017-02-23T22:22:48.271-0500 I REPL     [rsBackgroundSync] waiting for 3 pings from other members before syncing
2017-02-23T22:22:53.181-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27003
2017-02-23T22:22:53.182-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27003 - HostUnreachable: Connection refused
2017-02-23T22:22:53.183-0500 I REPL     [ReplicationExecutor] Error in heartbeat request to localhost:27003; HostUnreachable: Connection refused
2017-02-23T22:22:53.183-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27003
2017-02-23T22:22:53.183-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27003 - HostUnreachable: Connection refused
2017-02-23T22:22:53.184-0500 I REPL     [ReplicationExecutor] Error in heartbeat request to localhost:27003; HostUnreachable: Connection refused
2017-02-23T22:22:53.184-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27003
2017-02-23T22:22:53.185-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27003 - HostUnreachable: Connection refused
2017-02-23T22:22:53.185-0500 I REPL     [ReplicationExecutor] Error in heartbeat request to localhost:27003; HostUnreachable: Connection refused
2017-02-23T22:22:54.434-0500 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-02-23T22:22:54.434-0500 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-02-23T22:22:54.434-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27003
2017-02-23T22:22:54.435-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27003 - HostUnreachable: Connection refused
2017-02-23T22:22:54.435-0500 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received a yes vote from localhost:27002; response message: { term: 1, voteGranted: true, reason: "", ok: 1.0 }
2017-02-23T22:22:54.435-0500 I REPL     [ReplicationExecutor] dry election run succeeded, running for election
2017-02-23T22:22:54.436-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27003
2017-02-23T22:22:54.436-0500 I REPL     [ReplicationExecutor] VoteRequester(term 2) received a yes vote from localhost:27002; response message: { term: 2, voteGranted: true, reason: "", ok: 1.0 }
2017-02-23T22:22:54.436-0500 I REPL     [ReplicationExecutor] election succeeded, assuming primary role in term 2
2017-02-23T22:22:54.437-0500 I REPL     [ReplicationExecutor] transition to PRIMARY
2017-02-23T22:22:54.437-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27003 - HostUnreachable: Connection refused
2017-02-23T22:22:54.437-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27003
2017-02-23T22:22:54.437-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27002
2017-02-23T22:22:54.437-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27003
2017-02-23T22:22:54.437-0500 I REPL     [ReplicationExecutor] My optime is most up-to-date, skipping catch-up and completing transition to primary.
2017-02-23T22:22:54.438-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27003 - HostUnreachable: Connection refused
2017-02-23T22:22:54.438-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27003 - HostUnreachable: Connection refused
2017-02-23T22:22:54.438-0500 I REPL     [ReplicationExecutor] Error in heartbeat request to localhost:27003; HostUnreachable: Connection refused
2017-02-23T22:22:54.438-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27003
2017-02-23T22:22:54.439-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:27002
2017-02-23T22:22:54.439-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27003 - HostUnreachable: Connection refused
2017-02-23T22:22:54.439-0500 I REPL     [ReplicationExecutor] Error in heartbeat request to localhost:27003; HostUnreachable: Connection refused
2017-02-23T22:22:54.439-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27003
2017-02-23T22:22:54.440-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27003 - HostUnreachable: Connection refused
2017-02-23T22:22:54.440-0500 I REPL     [ReplicationExecutor] Error in heartbeat request to localhost:27003; HostUnreachable: Connection refused
2017-02-23T22:22:55.275-0500 I REPL     [rsSync] transition to primary complete; database writes are now permitted
2017-02-23T22:22:56.440-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27003
2017-02-23T22:22:56.442-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27003 - HostUnreachable: Connection refused
2017-02-23T22:22:56.442-0500 I REPL     [ReplicationExecutor] Error in heartbeat request to localhost:27003; HostUnreachable: Connection refused
2017-02-23T22:22:56.442-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27003
2017-02-23T22:22:56.443-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27003 - HostUnreachable: Connection refused
2017-02-23T22:22:56.443-0500 I REPL     [ReplicationExecutor] Error in heartbeat request to localhost:27003; HostUnreachable: Connection refused
2017-02-23T22:22:56.443-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27003
2017-02-23T22:22:56.444-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27003 - HostUnreachable: Connection refused
2017-02-23T22:22:56.444-0500 I REPL     [ReplicationExecutor] Error in heartbeat request to localhost:27003; HostUnreachable: Connection refused
2017-02-23T22:22:58.445-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27003
2017-02-23T22:22:58.446-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27003 - HostUnreachable: Connection refused
2017-02-23T22:22:58.446-0500 I REPL     [ReplicationExecutor] Error in heartbeat request to localhost:27003; HostUnreachable: Connection refused
2017-02-23T22:22:58.446-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27003
2017-02-23T22:22:58.447-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27003 - HostUnreachable: Connection refused
2017-02-23T22:22:58.447-0500 I REPL     [ReplicationExecutor] Error in heartbeat request to localhost:27003; HostUnreachable: Connection refused
2017-02-23T22:22:58.447-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27003
2017-02-23T22:22:58.448-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27003 - HostUnreachable: Connection refused
2017-02-23T22:22:58.448-0500 I REPL     [ReplicationExecutor] Error in heartbeat request to localhost:27003; HostUnreachable: Connection refused
2017-02-23T22:23:00.391-0500 I NETWORK  [thread1] connection accepted from 127.0.0.1:55812 #3 (2 connections now open)
2017-02-23T22:23:00.392-0500 I -        [conn3] end connection 127.0.0.1:55812 (2 connections now open)
2017-02-23T22:23:00.398-0500 I NETWORK  [thread1] connection accepted from 127.0.0.1:55820 #4 (2 connections now open)
2017-02-23T22:23:00.399-0500 I NETWORK  [conn4] received client metadata from 127.0.0.1:55820 conn4: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.0-rc3" }, os: { type: "Linux", name: "Fedora release 24 (Twenty Four)", architecture: "x86_64", version: "Kernel 4.6.7-300.fc24.x86_64" } }
2017-02-23T22:23:00.449-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27003
2017-02-23T22:23:00.451-0500 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:27003
2017-02-23T22:23:00.452-0500 I REPL     [ReplicationExecutor] Member localhost:27003 is now in state SECONDARY
2017-02-23T22:23:06.449-0500 I NETWORK  [thread1] connection accepted from 127.0.0.1:55834 #5 (3 connections now open)
2017-02-23T22:23:06.449-0500 I NETWORK  [conn5] received client metadata from 127.0.0.1:55834 conn5: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.0-rc3" }, os: { type: "Linux", name: "Fedora release 24 (Twenty Four)", architecture: "x86_64", version: "Kernel 4.6.7-300.fc24.x86_64" } }
2017-02-23T22:23:06.452-0500 I NETWORK  [thread1] connection accepted from 127.0.0.1:55838 #6 (4 connections now open)
2017-02-23T22:23:06.452-0500 I NETWORK  [conn6] received client metadata from 127.0.0.1:55838 conn6: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.0-rc3" }, os: { type: "Linux", name: "Fedora release 24 (Twenty Four)", architecture: "x86_64", version: "Kernel 4.6.7-300.fc24.x86_64" } }
2017-02-23T22:34:28.385-0500 I NETWORK  [thread1] connection accepted from 127.0.0.1:55846 #7 (5 connections now open)
2017-02-23T22:34:28.386-0500 I NETWORK  [conn7] received client metadata from 127.0.0.1:55846 conn7: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.0-rc3" }, os: { type: "Linux", name: "Fedora release 24 (Twenty Four)", architecture: "x86_64", version: "Kernel 4.6.7-300.fc24.x86_64" } }
2017-02-23T22:34:34.098-0500 I COMMAND  [conn7] Attempting to step down in response to replSetStepDown command
2017-02-23T22:34:34.098-0500 I REPL     [conn7] transition to SECONDARY
2017-02-23T22:34:34.098-0500 I NETWORK  [conn7] legacy transport layer closing all connections
2017-02-23T22:34:34.098-0500 I NETWORK  [conn7] Skip closing connection for connection # 6
2017-02-23T22:34:34.098-0500 I NETWORK  [conn7] Skip closing connection for connection # 5
2017-02-23T22:34:34.098-0500 I NETWORK  [conn7] Skip closing connection for connection # 4
2017-02-23T22:34:34.098-0500 I NETWORK  [conn7] Skip closing connection for connection # 2
2017-02-23T22:34:34.098-0500 I -        [conn7] AssertionException handling request, closing client connection: 172 Operation attempted on a closed transport Session.
2017-02-23T22:34:34.098-0500 I -        [conn7] end connection 127.0.0.1:55846 (5 connections now open)
2017-02-23T22:34:34.179-0500 I NETWORK  [thread1] connection accepted from 127.0.0.1:55848 #8 (4 connections now open)
2017-02-23T22:34:34.179-0500 I NETWORK  [conn8] received client metadata from 127.0.0.1:55848 conn8: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.0-rc3" }, os: { type: "Linux", name: "Fedora release 24 (Twenty Four)", architecture: "x86_64", version: "Kernel 4.6.7-300.fc24.x86_64" } }
2017-02-23T22:34:43.300-0500 I NETWORK  [thread1] connection accepted from 127.0.0.1:55856 #9 (5 connections now open)
2017-02-23T22:34:43.301-0500 I NETWORK  [conn9] received client metadata from 127.0.0.1:55856 conn9: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.0-rc3" }, os: { type: "Linux", name: "Fedora release 24 (Twenty Four)", architecture: "x86_64", version: "Kernel 4.6.7-300.fc24.x86_64" } }
2017-02-23T22:34:44.849-0500 I REPL     [ReplicationExecutor] Member localhost:27003 is now in state PRIMARY
2017-02-23T22:34:45.495-0500 I REPL     [rsBackgroundSync] sync source candidate: localhost:27003
2017-02-23T22:34:45.495-0500 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:27003
2017-02-23T22:34:45.498-0500 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:27003
2017-02-23T22:34:45.499-0500 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:27003
2017-02-23T22:34:45.501-0500 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:27003
2017-02-23T22:35:35.395-0500 I -        [conn6] end connection 127.0.0.1:55838 (6 connections now open)
2017-02-23T22:35:43.300-0500 I -        [conn4] end connection 127.0.0.1:55820 (5 connections now open)
2017-02-23T22:38:21.005-0500 I COMMAND  [repl writer worker 13] CMD: drop test.foo
2017-02-23T22:38:45.963-0500 I NETWORK  [thread1] connection accepted from 127.0.0.1:56014 #10 (4 connections now open)
2017-02-23T22:38:45.963-0500 I NETWORK  [conn10] received client metadata from 127.0.0.1:56014 conn10: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.0-rc3" }, os: { type: "Linux", name: "Fedora release 24 (Twenty Four)", architecture: "x86_64", version: "Kernel 4.6.7-300.fc24.x86_64" } }
2017-02-23T22:38:54.508-0500 I COMMAND  [conn10] terminating, shutdown command received
2017-02-23T22:38:54.508-0500 I NETWORK  [conn10] shutdown: going to close listening sockets...
2017-02-23T22:38:54.508-0500 I NETWORK  [conn10] closing listening socket: 7
2017-02-23T22:38:54.508-0500 I NETWORK  [conn10] closing listening socket: 8
2017-02-23T22:38:54.508-0500 I NETWORK  [conn10] removing socket file: /tmp/mongodb-27001.sock
2017-02-23T22:38:54.508-0500 I NETWORK  [conn10] shutdown: going to flush diaglog...
2017-02-23T22:38:54.508-0500 I REPL     [conn10] shutting down replication subsystems
2017-02-23T22:38:54.508-0500 I REPL     [conn10] Stopping replication reporter thread
2017-02-23T22:38:54.509-0500 I REPL     [SyncSourceFeedback] SyncSourceFeedback error sending update to localhost:27003: CallbackCanceled: Reporter no longer valid
2017-02-23T22:38:54.509-0500 I REPL     [conn10] Stopping replication fetcher thread
2017-02-23T22:38:54.509-0500 I REPL     [conn10] Stopping replication applier thread
2017-02-23T22:38:54.511-0500 I REPL     [conn10] Stopping replication storage threads
2017-02-23T22:38:54.511-0500 I FTDC     [conn10] Shutting down full-time diagnostic data capture
2017-02-23T22:38:54.515-0500 I STORAGE  [conn10] WiredTigerKVEngine shutting down
2017-02-23T22:38:55.018-0500 I STORAGE  [conn10] shutdown: removing fs lock...
2017-02-23T22:38:55.018-0500 I CONTROL  [conn10] now exiting
2017-02-23T22:38:55.018-0500 I CONTROL  [conn10] shutting down with code:0
